//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePedidos
    {
        public int DetalleId { get; set; }
        public Nullable<int> PedidoId { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<bool> TieneIVA { get; set; }
        public Nullable<decimal> SubtotalLinea { get; set; }
        public Nullable<decimal> IVALinea { get; set; }
    
        public virtual Pedidos Pedidos { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
